name: Run PHPStan
on:
  workflow_call:
    secrets:
      env:
        required: false
    inputs:
      extensionName:
        description: "Your extension name"
        required: true
        type: string
      shopwareVersion:
        description: |
          With the default `.auto`, the workflow tries to find a shopware version using the shopware-version action.

          For example, if the current ref is next-1234, it will try to find the ref next-1234 in shopware/shopware. If there's no matching ref, it will use shopwareVersionFallback
        required: false
        type: string
        default: ".auto"
      shopwareVersionFallback:
        required: false
        type: string
        default: trunk
      shopware-repository:
        description: The shopware repository to checkout
        type: string
        default: shopware/shopware
      composerRootVersion:
        required: false
        type: string
        default: ".auto"
      dependencies:
        required: false
        type: string
      extraRepositories:
        required: false
        type: string
        description: |
          Additional composer repositories
          Example:
            {
              "customRepo": {
                "type": "vcs",
                "url": "https://my-custom-repo.example.test/foo/bar.git"
              }
            }
        default: "{}"
      runner:
        required: false
        type: string
        default: ubuntu-latest
env:
  SHOPWARE_TOOL_CACHE_PHPSTAN: ${{ github.workspace }}/var/phpstan

jobs:
  run:
    name: Static Analyse
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Setup Shopware
        uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: ${{ inputs.extensionName }}
          shopwareVersion: ${{ inputs.shopwareVersion }}
          shopwareVersionFallback: ${{ inputs.shopwareVersionFallback }}
          shopware-repository: ${{ inputs.shopware-repository }}
          composerRootVersion: ${{ inputs.composerRootVersion }}
          phpVersion: 8.2
          env: prod
          install: "true"
          dependencies: ${{ inputs.dependencies }}
          extraRepositories: ${{ inputs.extraRepositories }}
      - name: Create phpstan.neon
        working-directory: custom/plugins/${{ inputs.extensionName }}
        run: |
          printf "parameters:\n  tmpDir: ${{ env.SHOPWARE_TOOL_CACHE_PHPSTAN }}\nincludes:\n  - phpstan.neon.dist" > phpstan.neon
      - name: PHPStan cache
        uses: actions/cache@v4
        with:
          path: ${{ env.SHOPWARE_TOOL_CACHE_PHPSTAN }}
          key: ${{ runner.OS }}-${{ github.repository }}-phpstan-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpstan-
      - name: Build PHPStan Bootstrap
        run: php ${{ github.workspace }}/src/Core/DevOps/StaticAnalyze/phpstan-bootstrap.php
      - name: Run PHPStan
        working-directory: custom/plugins/${{ inputs.extensionName }}
        run: ${{ github.workspace }}/vendor/bin/phpstan analyze --error-format=github --no-progress
